enum FavoriteCategory: String, CaseIterable {
//    case food = "FOOD"
//    case place = "PLACE"
//    case product = "PRODUCT"
//    case person = "PERSON"
//    case service = "SERVICE"
//    case sports = "SPORTS"
//    case artist = "ARTIST"
//    case book = "BOOK"
//    case movie = "MOVIE"
//    case other = "OTHER"
    case food = "1"
    case place = "2"
    case product = "3"
    case person = "4"
    case service = "5"
    case sports = "6"
    case artist = "7"
    case book = "8"
    case movie = "9"
    case other = "10"
}
